In [4]:
import numpy as np

In [26]:
#Create a list to store the daily sales of a local shop
daily_sales_list=[100,150,50,250,190,160,200]

In [27]:
#Convert this list to a numpy array
daily_sales=np.array(daily_sales_list)

In [9]:
daily_sales

array([100, 150,  50, 250, 190, 160, 200])

In [13]:
#Array properties
print("Sales array: ",daily_sales)
print("Type of daily_sales: ",type(daily_sales))
print("Datatype of elements in daily_sales: ",daily_sales.dtype)
print("Shape of daily_sales: ",daily_sales.shape)
print("Number of dimensions of daily_sales: ",daily_sales.ndim)

Sales array:  [100 150  50 250 190 160 200]
Type of daily_sales:  <class 'numpy.ndarray'>
Datatype of elements in daily_sales:  int64
Shape of daily_sales:  (7,)
Number of dimensions of daily_sales:  1


In [28]:
#Simple operations
#Lets say there was initially a 10% discount
discount_factor=0.9
discount_sales= daily_sales * discount_factor
print("Discounted prices(10%): ",discount_sales) #Note that here the output will be in float, like 90. 135. here . means its float 90.0 but shortened,
#you can make the output integer by using .astype(int)
print("Integer valued discounted price: ",discount_sales.astype(int))

Discounted prices(10%):  [ 90. 135.  45. 225. 171. 144. 180.]
Integer valued discounted price:  [ 90 135  45 225 171 144 180]


In [21]:
#Lets add a shipping price of $5
total_price= daily_sales + 5
print("Prices after adding shipping charge: ",total_price)

Prices after adding shipping charge:  [105 155  55 255 195 165 205]


In [23]:
#Compare the sales to a target value
profit_days= daily_sales > 170
print("Days with high profit: ",profit_days)

Days with high profit:  [False False False  True  True False  True]


In [36]:
#Indexes
print("Sales on day 1: ",daily_sales[0])
print("Sales on last day: ",daily_sales[-1])
print("Sales on first three days: ",daily_sales[0:3])
print("Sales on day 4 and 7: ",daily_sales[[3,6]])

Sales on day 1:  100
Sales on last day:  200
Sales on first three days:  [100 150  50]
Sales on day 4 and 7:  [250 200]


In [38]:
#Reshape the array
new_sales=daily_sales.reshape(7,1)
new_sales

array([[100],
       [150],
       [ 50],
       [250],
       [190],
       [160],
       [200]])

In [39]:
#Make a sale for 6 days, sunday->shop closed
sales_array=[100,150,50,250,190,160]

In [40]:
sales_array= np.array(sales_array)

In [48]:
sales_array=sales_array.reshape(2,3)
sales_array

array([[100, 150,  50],
       [250, 190, 160]])

In [49]:
#access a value in this 2D array
sales_array[0,2]

np.int64(50)

In [69]:
#If i want the first row, 0->first row and :->all col
print("Sales of first three days: ",sales_array[0])

#note that 1:5 means give me row with index 1 till row with index 5(excluded) meaning itll give you 2nd,3rd,4th row
print("Sales of first three days: ",sales_array[1:5]) #Note if it is [3:5] returns []
#OR
print("Sales on last three days: ",sales_array[1,:])

Sales of first three days:  [100 150  50]
Sales of first three days:  [[250 190 160]]
Sales on last three days:  [250 190 160]
Sales on last three days:  250


In [71]:
daily_sales

array([100, 150,  50, 250, 190, 160, 200])

In [95]:
#Aggregate Function
print("Total sales: ",np.sum(daily_sales))
print("Average sales: ",round(np.mean(daily_sales),2))
print("Max sale: ",np.max(daily_sales))
print("Day of max sale: ",np.argmax(daily_sales)+1) #argmax->index

print("Min sale: ",np.min(daily_sales))
print("Day of min sale: ",np.argmin(daily_sales)+1)
print("Middle value of sale: ",np.median(daily_sales))
print("Daily sales differ from mean by: ",round(np.std(daily_sales),2))

Total sales:  1100
Average sales:  157.14
Max sale:  250
Day of max sale:  4
Min sale:  50
Day of min sale:  3
Middle value of sale:  160.0
Daily sales differ from mean by:  61.35


In [113]:
#Creating arrays with specific values
np.zeros((2,3)).astype(int)
np.ones((3,4))
np.full((2,3),3)
np.eye(3,3)
np.random.rand(3,3)
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [117]:
#Concatenate array
more_sales=np.array([135,370])
combined_sales=np.concatenate((daily_sales,more_sales))
print("More sales data: ",combined_sales)

More sales data:  [100 150  50 250 190 160 200 135 370]


In [124]:
#Splitting an array
half=np.split(combined_sales,3)
print("Split in Three halves: ",half)
#split at a particular index
np.split(combined_sales,[4])

Split in Three halves:  [array([100, 150,  50]), array([250, 190, 160]), array([200, 135, 370])]


[array([100, 150,  50, 250]), array([190, 160, 200, 135, 370])]